### ISSUE TITLE
tests audio

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#10]
tests audio avec un micro RODE NT USB 
molette maximum:
https://codecast.france-ioi.org/player?id=1463739936987
molette minimum:
https://codecast.france-ioi.org/player?id=1463740160921
Préférences système input max:
https://codecast.france-ioi.org/player?id=1463740660791

tests audio avec micro intégré macbook pro:
input max, réduction de bruit ON
https://codecast.france-ioi.org/player?id=1463741085145
input max, réduction de bruit OFF:
https://codecast.france-ioi.org/player?id=1463741290677

Je pense qu'il y a un problème avec la compression MP3.
L'exemple flagrant est au temps: 00:51  , 00:53 à 00:56  ,  01:03 à 01:05 :
https://codecast.france-ioi.org/player?id=1463741290677

**Comment by epixode** [comment]
Je me demande si ce n'est pas plutôt l'interpréteur javascript qui perd des buffers audio lorsque d'autres évènements (clavier, souris) entrent en concurrence.  Est-ce que tu as pu confirmer avec le fichier WAV si ces artefacts apparaissent aussi dans le flux non compressé ?

**Comment by remisharrock** [comment]
je pense effectivement que c'est un problème qui n'arrive que dans un cas très particulier (dans mon bureau) - pour le moment les enregistrements que je fais ne sont pas impactés car j'ai changé d'environnement.

**Comment by Manouchehri** [comment]
The audio demo works perfectly, nice job!

Looking forward to using this project in the future.
