### ISSUE TITLE
Technique d'enregistrement des modifications du DOM (mutation?) Souris !

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#107]
Salut Seb, J'ai trouvé ce code qui enregistre les modifications du DOM et qui les rejoue. Est-ce que tu utilises la même technique? 

https://jsbin.com/nemake/edit?js,output

Celle-ci permet d'enregistrer la souris également, qu'en penses-tu avec les players à différents formats? ça peut marcher? https://scrimba.com/ le fait mais ça marche pas très bien ya plein de bugs....

(trouvé sur https://stackoverflow.com/a/42078213)

**Comment by epixode** [comment]
En enregistrant les modifications du DOM, le comportement obtenu est plus celui d'une vidéo, qu'on peut rejouer mais avec laquelle on ne peut pas interagir.  Codecast utilise une approche différente pour permettre de mettre en pause à n'importe quel moment et d'interagir immédiatement avec l'évaluateur pas à pas.

Pour la position de la souris, l'approche de scrimba est d'avoir une interface "pleine fenêtre" et d'enregistrer les déplacements de la souris indépendemment de la taille de la fenêtre.  Je ne vois pas comment ça peut bien fonctionner en mélangeant des éléments d'interface de taille fixe et d'autres qui se mettent à l'échelle, je ne suis pas surpris que aies constaté des problèmes.

La seule solution simple et fiable que je voie qui permette d'enregistrer les déplacements de la souris, serait de figer complètement la taille de tous les éléments d'interface.  Ce n'est pas une solution robuste avec l'approche de codecast: un changement dans l'interface pourrait rendre incorrecte un enregistrement existant.

Une approche alternative serait d'ajouter un mécanisme permettant d'enregistrer des évènements plus haut niveau, comme "le curseur de la souris se situe au dessus de tel bouton (ou telle ligne/colonne de l'éditeur, etc)".  Et d'interpoler les déplacement de la souris entre ces points.  Le résultat serait fiable et robuste, mais l'approche n'est pas du tout simple.

**Comment by remisharrock** [comment]
Ok c'est clair 💯 Autre question: pour enregistrer et rejouer les modifications dans une zone de code pour n'importe quel langage (genre ACE uniquement) sans rien d'autre (pas d'évaluateur), en imaginant que la zone de code ait une taille fixe, est-ce que cette méthode suffit et permet-elle de faire pause, reprendre le contrôle de la zone de code puis relecture, comme codecast?

**Comment by remisharrock** [comment]
Je viens de tester avec https://jsbin.com/nemake/edit?js,output  dans la petite zone input text :
Si on modifie le texte dans cette zone en cours de lecture, les modifications futures ne sont pas prises en compte effectivement. 
Il faut du coup pouvoir faire pause, enregistrer le DOM quand on fait pause et remettre le DOM enregistré si on fait play de nouveau... 
Mais du coup je vois pas comment tu implémentes avec ta navigation temporelle, c'est quand même super efficace Codecast quand on navigue dans le temps ! Tu m'avais expliqué ton secret mais j'ai oublié :)

**Comment by epixode** [comment]
Codecast n'utilise que des vue pures (sans effets de bord) dont le rendu est un DOM virtuel, react s'occupant de synchroniser ce DOM virtuel avec le DOM réel.  La navigation temporelle se réduit à passer un état différent aux vues.  Pour que ce soit efficace en terme d'utilisation mémoire, codecast n'utilise que des structures de données persistentes (non mutables) pour représenter son état, ce qui permet de partager tout ce qui n'a pas été modifié entre un instant t et l'instant t+1.

**Comment by mathias-hiron** [comment]
Pour les discussions sur les évolutions futures possibles de codecast, nous utiliserons désormais un document séparé, et non des issues github.
