### ISSUE TITLE
Language Server Protocol

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#108]
ACE est un très bon éditeur, mais ne supporte pas le Language Server Protocol. L'editeur Monaco le supporte par exemple:

https://typefox.io/teaching-the-language-server-protocol-to-microsofts-monaco-editor

Ceci permet d'avoir des fonctionnalités du style "intellisense" d'autocompletion intelligentes comme le montre la démo ici http://52.29.251.2/calcmonaco/ 

En interne, voici l'explication:

The Monaco Editor Language Client provides a language client that establishes communication between Monaco editors and language servers over JSON-RPC and the VSCode WebSocket JSON-RPC package enables JSON-RPC to work over web sockets.

Une équivalence pour ACE existe-t-elle ?

**Comment by epixode** [comment]
Je pense qu'il ne faut pas perdre de vue l'objectif pédagogique de codecast.  Intégrer de l'autocomplétion "intelligente", dont l'objectif est un gain de productivité, ne me semble pas contribuer de manière significative à l'objectif principal qui est de comprendre finement ce que l'on écrit.

**Comment by remisharrock** [comment]
Oui pour l'autocompletion, après il y a aussi d'autres avantages au support du Language Server Protocol pour l'apprentissage de la programmation:
- vérification de la syntaxe : on peut souligner en rouge, jaune qui peut guider pour l'apprentissage. 
- semantic coloration (en plus de syntaxic coloration): ça j'adore ! C'est très bon pédagogiquement, exemple https://medium.com/@evnbr/coding-in-color-3a6db2743a1e 
- explication des fonctions quand on passe la souris dessus: description, paramètres etc...
- jump to definition: pour arriver directement à la déclaration d'une variable, d'une fonction
- find references: pour arriver directement à l'appel d'une fonction
- recherche de symboles
- renommer/refactoring intelligent (ça c'est plus productivité que pédagogique)
- surement d'autres que j'oublie

Il me semble que sur le long terme, avoir le support du Language Server Protocol est une bonne chose pédagogiquement :)

**Comment by remisharrock** [comment]
Tout à fait! 
Je fais de la veille technologique pour le futur à long terme de Codecast ;)
ACE n'a pas avancé de ce côté: https://github.com/ajaxorg/ace/issues/3124 
Pour répondre à ta question, il existe de nombreuses implémentations du langage server protocol pour tous les langages de programmation. Tout est open source.
Un exemple pour le langage c est le serveur cquery https://github.com/cquery-project/cquery 
 Il supporte notamment le "semantic highlighting" avec support du [rainbow semantic highlighting](https://medium.com/@evnbr/coding-in-color-3a6db2743a1e)

Ok pour Monaco, il faut tout de même continuer à faire de la veille sur Language Server Protocol qui est maintenant un standard incontournable.

**Comment by remisharrock** [comment]
liens importants:
https://github.com/Microsoft/language-server-protocol
Specification:
https://microsoft.github.io/language-server-protocol/specification
Implementations:

**Comment by remisharrock** [comment]
https://microsoft.github.io/language-server-protocol/implementors/servers/

**Comment by mathias-hiron** [comment]
Pour les discussions sur les évolutions futures possibles de codecast, nous utiliserons un document séparé, et non des issues github.
