### ISSUE TITLE
Location of build directory

### ISSUE THREAD

**Issue by Vm900** [France-ioi/codecast#143]
Just built c-to-json,however i don't see the build directory mentioned in the instructions.
Thanks

**Comment by GeoffreyHuck** [comment]
Hello !

As mentioned there :  https://github.com/epixode/c-to-json/issues/1#issuecomment-390388305 you can directly retrieve the binary here :

```
$ curl -O https://codecast.france-ioi.org/next/c-to-json
$ sha1sum c-to-json 
d517a2e95a13ab66fe106443c12aff9764026944  c-to-json
```

As there are some problems currently with the c-to-json build.

Hope this helps !
