### ISSUE TITLE
Can't build the program

### ISSUE THREAD

**Issue by Vm900** [France-ioi/codecast#144]
Hi,
Just been trying to build a local copy and i keep getting the following error:
npm install

> speaker@0.3.1 install /home/vmur/codecast/node_modules/speaker
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/vmur/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/vmur/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/vmur/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/vmur/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/vmur/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/vmur/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Linux 5.4.7-1
gyp ERR! command "/home/vmur/.nvm/versions/node/v12.14.1/bin/node" "/home/vmur/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vmur/codecast/node_modules/speaker
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN react-clickdrag@3.0.2 requires a peer of react@0.14.x || ^15.0.0-rc but none is installed. You must install peer dependencies yourself.
npm WARN react-clickdrag@3.0.2 requires a peer of react-dom@0.14.x || ^15.0.0-rc but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: speaker@0.3.1 (node_modules/speaker):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: speaker@0.3.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 11007 packages in 46.789s

24 packages are looking for funding
  run `npm fund` for details

found 9 vulnerabilities (4 low, 2 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
====================================================
Help thanks

**Comment by GeoffreyHuck** [comment]
Hello ! Does this thread on stackoverflow https://stackoverflow.com/questions/14772508/npm-failed-to-install-time-with-make-not-found-error help ?

**Comment by Vm900** [comment]
No.Not at all.

**Comment by GeoffreyHuck** [comment]
What system are you on ?

**Comment by Vm900** [comment]
Sorry for the late reply.I'm kaos linux

**Comment by GeoffreyHuck** [comment]
I'm not sure how you can do this with kaos linux but you need to install the "make" package.

**Comment by Vm900** [comment]
Oh sorry i thought your question was about my os.I have make alreadt=y installed

**Comment by GeoffreyHuck** [comment]
Yes it was, from your error message it looks like make is not installed, or that it cannot be found. Maybe it is a problem with $PATH, but since I don't know kaos linux I'm not sure how I can help you further. I can suggest you to search help within the kaos linux community.
