### ISSUE TITLE
python: variable name "name"

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#160]
when using "name" as a variable, in the variable list on the left, the name is "name_$rn$" 

![image](https://user-images.githubusercontent.com/8048877/102484549-b7d58e00-4066-11eb-8b5a-8689bbef20b4.png)

thank you !

**Comment by remisharrock** [comment]
of course it does not do that if we change name by x:
![image](https://user-images.githubusercontent.com/8048877/109144491-86152d80-7761-11eb-92c9-88d15529aa9f.png)

**Comment by SebastienTainon** [comment]
Indeed, Skulpt adds a suffix to variables that have a reserved name. Now the suffix is being removed on the Codecast dev platform.
