### ISSUE TITLE
float variables values should be displayed with decimal notation in the variable pane

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#163]
when using float variables, the variable pane on the left should displayed with a decimal notation.
For example it should be z = 3.0 instead of z=3 on the left. 
The prints are OK in the terminal though @GeoffreyHuck 
![image](https://user-images.githubusercontent.com/8048877/109146442-210f0700-7764-11eb-9761-5d71c698c080.png)

code 
```
x = str(3)    # x will be '3'
y = int(3)    # y will be 3
z = float(3)  # z will be 3.0

print(x)
print(y)
print(z)
```

**Comment by SebastienTainon** [comment]
Same as #167? Let me know if it's the not the case.
