### ISSUE TITLE
the return of the type() function does not appear in the variable pane but prints OK

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#164]
when receiving the return of the type() function in a variable, it does not appear in the variable pane on the left but it prints OK in the terminal. Maybe because it is of type class ? @GeoffreyHuck 

![image](https://user-images.githubusercontent.com/8048877/109146828-97ac0480-7764-11eb-9897-b45a3f7880f1.png)

code

```
x = 5
y = "John"
tx = type(x)
ty = type(y)

print(tx)
print(ty)
```

**Comment by SebastienTainon** [comment]
This was because a the `type(x)` returns the type itself, which is a JS class. It's now handled properly on the Codecast dev platform and the variable type is correctly shown.
