### ISSUE TITLE
complex types are not displayed in the variable pane

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#166]
example:
![image](https://user-images.githubusercontent.com/8048877/109386331-4a619b80-78fa-11eb-9005-265b7223ead2.png)
@GeoffreyHuck 
code

```
x = 1j

#display x:
print(x)

#display the data type of x:
print(type(x)) 

```

**Comment by SebastienTainon** [comment]
Complex types are now displayed in the variable pane in the Codecast dev platform.
