### ISSUE TITLE
exact float number do not appear with decimal notation in the variable pane

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#167]
for example 20.0 should be displayed 20.0 and not 20
@GeoffreyHuck 
example
![image](https://user-images.githubusercontent.com/8048877/109386381-a2000700-78fa-11eb-93cd-90dbc2c540d6.png)
when trying on http://skulpt.org/using.html  it works
code 
```
x = 20.0

#display x:
print(x)

#display the data type of x:
print(type(x)) 
```

**Comment by SebastienTainon** [comment]
This is now fixed on the development platform :)

**Comment by remisharrock** [comment]
Thank you, is the "development platform" hosted here ? https://codecast.france-ioi.org/next/ 
if so, I don't see any difference, if not, is there a public link to the dev platform ?

**Comment by remisharrock** [comment]
I just found the link in issue https://github.com/France-ioi/codecast/issues/173 
http://3.126.86.182:8001/next
but I have this error:

Source: stepper

TypeError: Cannot read property 'reset' of undefined
Thanks for your help !
