### ISSUE TITLE
tuples are displayed as an empty list in the variable pane

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#168]
example

![image](https://user-images.githubusercontent.com/8048877/109386485-3a968700-78fb-11eb-9641-22ba40384076.png)

should be tuple instead of list and the content should be displayed also
@GeoffreyHuck 
code

```
x = ("apple", "banana", "cherry")

#display x:
print(x)

#display the data type of x:
print(type(x)) 


```

**Comment by SebastienTainon** [comment]
Now the type of the variable is "tuple" and the values are displayed in the Codecast dev platform.
