### ISSUE TITLE
range are of type list and not range (maybe a skulpt problem)

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#169]
when using a range, the variable pane does not display the type 'range' neither 'list' but is empty intead ('list' appears when using lists)
in the terminal, the type is list instead of range

![image](https://user-images.githubusercontent.com/8048877/109386542-8b0de480-78fb-11eb-94e8-999ae3ab33e4.png)

when trying with https://www.w3schools.com/python/trypython.asp?filename=demo_type_range  we get the type 'range'
when trying with http://skulpt.org/using.html  we get 'list' so it might be a skulpt problem
@GeoffreyHuck 
code 

```
x = range(6)

#display x:
print(x)

#display the data type of x:
print(type(x)) 

```

**Comment by remisharrock** [comment]
linked to https://github.com/skulpt/skulpt/issues/979

**Comment by SebastienTainon** [comment]
Now that this Skulpt issue has been resolved, ranges are now indicated as range on the Codecast dev platform.
