### ISSUE TITLE
dictionnaries should be displayed as 'dict' instead of 'obj' in the variable pane when folded

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#170]
when folded, a dict appears as an obj in the variable pane. terminal is OK and displayed as 'dict' 
when unfolded, obj disapears
@GeoffreyHuck 

example: 
![image](https://user-images.githubusercontent.com/8048877/109386661-72ea9500-78fc-11eb-8e80-90eefce3852d.png)
code
```
x = {"name" : "John", "age" : 36}

#display x:
print(x)

#display the data type of x:
print(type(x)) 

```

**Comment by SebastienTainon** [comment]
Thanks, that's now fixed on the development platform.
