### ISSUE TITLE
frozenset in the new version of skulpt

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#172]
frozenset seems to be impleted recently in skulpt, can we integrate this ? 

![image](https://user-images.githubusercontent.com/8048877/109386775-6450ad80-78fd-11eb-90b4-9bcd2086719a.png)

related to

https://github.com/skulpt/skulpt/issues/1029

@GeoffreyHuck

**Comment by SebastienTainon** [comment]
Frozensets are now implemented in the Codecast dev platform.
