### ISSUE TITLE
boolean types in the variable pane are displayed as integer values 1 or 0

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#173]
example
![image](https://user-images.githubusercontent.com/8048877/109386807-99f59680-78fd-11eb-8e5d-bb714afb753d.png)

should be True and not 1

same for False, should be False and not 0

@GeoffreyHuck

**Comment by SebastienTainon** [comment]
Hello @remisharrock ,
I've just started to work on Codecast. I've checked this issue and made a fix for it.
I give you the link of the current development platform so that you can try this fix out: http://3.126.86.182:8001/next
Let me know if you have questions about this.
