### ISSUE TITLE
are bytes compatible with skulpt ?

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#174]
example:

![image](https://user-images.githubusercontent.com/8048877/109386892-2c963580-78fe-11eb-8d0a-46238d8369c3.png)

code
```
x = b"Hello"

#display x:
print(x)

#display the data type of x:
print(type(x)) 

```
related to :
https://github.com/skulpt/skulpt/issues/909

@GeoffreyHuck

**Comment by SebastienTainon** [comment]
@remisharrock This is because we currently don't appear to use the latest Skulpt version. The latest Skulpt version allows for such byte strings. I plan to update soon, I'll keep you informed ;)

**Comment by SebastienTainon** [comment]
Hello @remisharrock, I've just made the update to the most recent stable Skulpt version (which is 1.3) on the development platform (https://codecast-dev.france-ioi.org/next/task). You now have bytes support on this one. Don't forget to change language to Python to try it :)
