### ISSUE TITLE
dev platform TypeError: Cannot read property 'reset' of undefined

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#192]
as explained here https://github.com/France-ioi/codecast/issues/167 
I have the following error on the dev platform http://3.126.86.182:8001/next 

Source: stepper

TypeError: Cannot read property 'reset' of undefined

thanks for your help

**Comment by SebastienTainon** [comment]
Hello @remisharrock 
Sorry I had wrong notification settings for this repository and I missed your issue.
The new dev platform is on this URL: https://codecast-dev.france-ioi.org/next/task
