### ISSUE TITLE
URGENT: sablier/banière d'attente pour la progression du chargement à remonter

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#202]
Bonjour, on vient d'implémenter les iframe avec hauteur fixe en pixels et le résultat est que la barre de progression s'affiche trop bas sur beaucoup d'écrans, ce qui, pendant toute la durée du chargement fait penser à un bug puisque l'étudiant voit du noir/gris. Pouvez-vous dédoubler cette barre en haut ou bien mettre un message en haut ? voici le résultat actuel:
![image](https://user-images.githubusercontent.com/8048877/120488672-4ccf0800-c3b7-11eb-82f8-cf6f57d93b00.png)

**Comment by mblockelet** [comment]
J'ai fait une correction rapide qui devrait afficher la barre en haut à la place du milieu. C'est une correction rapide, qui du coup va afficher les autres dialogs en haut plutôt qu'au milieu, mais je vais faire une correction plus pérenne d'ici peu.

**Comment by mblockelet** [comment]
Voilà, la barre de chargement va s'afficher en haut, sans affecter les autres dialogs !
