### ISSUE TITLE
Terminal overflow text on new codecast

### ISSUE THREAD

**Issue by AadhyaKocha** [France-ioi/codecast#230]
On this [Codecast link](https://codecast.france-ioi.org/v7/task?recording=https%3A%2F%2Ffioi-recordings.s3.amazonaws.com%2Fdartmouth%2F1518633303037) when forwarded to over 2min 12s, there is text in the terminal. If the browser window is small that text continues to flow outside the terminal into the white space and is not seen rather than wrapping around inside the terminal. I have attached an image of the same:
![Screenshot 2022-01-20 at 9 47 03 AM](https://user-images.githubusercontent.com/51734801/150361331-f8eee088-380a-481d-af7b-9ecc2ceeda5f.png)

**Comment by SebastienTainon** [comment]
Thanks for reporting! The responsive terminal has now been deployed to v7 and thus this is fixed.
