### ISSUE TITLE
player : visualisation tableau avec indices, compréhension du i barré

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#26]
Je ne comprends pas le premier i barré dans cet enregistrement:
https://codecast.france-ioi.org/player?id=1464267987308
De plus, peut-on afficher une couleur ou un truc à droite du tableau quand on tape en dehors des bornes ?

**Comment by epixode** [comment]
Le i est barré au moment où 0 est écrit dans la variable lors de son initialisation en début de boucle.  Le fait que la valeur précédente et la nouvelle valeur soient identiques est indépendant, on masquer l'affichage de l'écriture dans ce cas.

Pour la deuxième question, il ne me semble pas que ça ait du sens en C car les écritures dans un tableau se font par arithmétique de pointeurs (même une déclaration int a[2] indique qu'il faut allouer 2 int pour a, l'expression "a" elle-même a type int* et ne porte plus d'indication de la "taille" de la zone pointée).

Si on essayait d'ajouter artificiellement à l'évaluateur un mécanisme de "range checking", on observerait pour 2 tableaux alloués de manière adjacente dans la pile, qu'une écriture dans l'un des tableaux serait affichée comme une écriture "hors bornes" dans l'autre tableau.  Il n'est pas possible de deviner l'intention de l'utilisateur.
