### ISSUE TITLE
Codecast Pause button crashes the recording

### ISSUE THREAD

**Issue by Skyepulse** [France-ioi/codecast#272]
When recording a codecast, pressing the pause button makes the rest of the buttons (pause, play and stop) unable to be pressed. There is no way to restart the recording without refreshing the page: the audio is then lost.
![image](https://user-images.githubusercontent.com/59956921/228289095-510f8a9f-b993-42d1-82d5-70de6766ad82.png)

When pressing the pause button, these errors can be found in the console:
![image](https://user-images.githubusercontent.com/59956921/228289834-9911689f-bdf2-4243-9598-8b17e80cc09e.png)

https://user-images.githubusercontent.com/59956921/228289822-fdbd12d4-49c8-42ac-a44b-ec7dbf77c232.mp4

**Comment by SebastienTainon** [comment]
This should now be solved :smile:
