### ISSUE TITLE
Lors de l'enregistrement d'un codecast pas de répertoire guest par défaut disponible

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#274]
voir la description ici 
https://github.com/remisharrock/pythonspace/issues/45

**Comment by SebastienTainon** [comment]
Le répertoire guest n'est accessible que pour les guests, c'est-à-dire les utilisateurs non connectés :)

PS : je n'ai pas accès au repo du lien donné

**Comment by remisharrock** [comment]
je t'ajoute de suite @SebastienTainon  !

**Comment by SebastienTainon** [comment]
![image](https://user-images.githubusercontent.com/5164914/233020082-1c6b91e8-f9df-4284-b0b8-ceceb2b915f8.png)

There is now a Logout button in front of the Target field so that the user can select another Algorea account or simply Guest to access other targets.

**Comment by remisharrock** [comment]
a priori c'est bon lors d'un enregistrement (testé avec Marie) mais par contre lors de l'édition d'un codecast existant, ce bouton n'existe pas; es-til possible de l'ajouter également pour l'édition ?

**Comment by MarieVM** [comment]
Voici l'endroit où ce bouton serait utile:

![image](https://user-images.githubusercontent.com/77794506/234327134-6c78a49b-e227-42b1-a3a5-fed01bde5f47.png)

**Comment by SebastienTainon** [comment]
J'ai ajouté le bouton aussi dans l'écran d'enregistrement de l'éditeur.
