### ISSUE TITLE
Bug lié à la possibilité de choisir le langage de programmation codecast

### ISSUE THREAD

**Issue by Skyepulse** [France-ioi/codecast#296]
Lorsque l'on accède à un codecast à travers une URL qui n'a pas "?platform=python" ou autre langage à la fin (Ex: https://static-items.algorea.org/files/checkouts/5843a0bc640d507f1add0520148d5243/algorea_serious_game/06_variables_laser_01/index_codecast.html), et on accède aux réglages, on peut changer le langage de programmation souhaité (en dessous de la langue) et cela crashe parfois avec certaines combinaisons (C/arduino par exemple).

**Comment by remisharrock** [comment]
Bonjour, cette erreur est toujours d'actualité même en intégration sur fun-mooc après un test, ceci est embêtant et devrait être réparé avant le déploiement sur FUN-MOOC . merci !

**Comment by SebastienTainon** [comment]
Bonjour  @remisharrock , pour ne pas faire apparaître le choix des langages de programmation, il suffit de mettre "?platform=..." avec le nom de la plateforme. Si ce n'est pas mis, tous les langages supportés par Codecast apparaissent, je ne pense pas que ce soit un comportement souhaité pour une intégration car un certain nombre de ces langages risquent de ne pas correspondre aux tâches ciblées.

**Comment by SebastienTainon** [comment]
Par défaut, à partir de Codecast 7.3 les langages supportés par la lib robot sont Blockly, Python et Scratch. J'ai mis à jour les sujets algorea_serious_game vers Codecast 7.3 (ils étaient précédemment sur Codecast 7.2).
