### ISSUE TITLE
en python activer la catégorisation par défaut 

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#301]
est-ce possible d'activer systématiquement la catégorisation des blocs par défaut quel que soit le nombre de "blocs" disponibles et/ou le nombre d'étoiles (difficulté). 
Il faudrait également que toutes les catégories soient "ouvertes" par défaut pour éviter de les cacher au départ + économiser des clics d'ouverture. 
merci

**Comment by MarieVM** [comment]
Comment fonctionne le choix d'ouverture des catégories ?

**Comment by remisharrock** [comment]
effectivement, si on ouvre tout on peut se retrouver avec une liste beaucoup trop longue...

**Comment by SebastienTainon** [comment]
Oui j'ai discuté avec Mathias, on ne pense pas que ce soit une bonne idée au final : autant ne pas avoir de catégorie dans ce cas si tout est ouvert par défaut au chargement.
