### ISSUE TITLE
Associer un enregistrement audio à un exercice codecast

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/codecast#310]
Une fois qu’on enregistre un codecast audio, l’URL statique générée est différente de celle de l’exercice associé sur svn import et il n’y a pas d’URL LTI, comment faire ? 
Comment associer un enregistrement audio à un exercice codecast ? 
Comment générer un lien LTI pour intégrer l'exercice et l'enregistrement audio associé ? 
En effet, l'URL statique générée pour un exercice sur svn est différente de l'URL statique générée via l'interface de création de codecast. Ce qui est normal. Mais dans le cas de la création d'un codecast, l'utilisateur ne dispose pas de la possibilité de générer un lien LTI pour intégration sur un LMS. 
![image](https://github.com/France-ioi/codecast/assets/19490273/a3f82233-3324-4ad9-87ed-40ed45d33386)

![image](https://github.com/France-ioi/codecast/assets/19490273/b33fb351-d6f1-43f4-a79a-84457cc96452)

**Comment by SebastienTainon** [comment]
L'écran d'enregistrement de l'enregistrement propose à présent l'URL LTI de l'enregistrement, en plus des autres URL déjà présentes :)
