### ISSUE TITLE
Sélectionner un niveau dans l'URL Codecast avec "level=medium" renvoie sur le level "basic"

### ISSUE THREAD

**Issue by avirouleau** [France-ioi/codecast#312]
ancienne URL : https://static-items.algorea.org/files/checkouts/bb3471a19ecc5f3ddf5f5575aeec3516/01_sequence_05_course/index.html?language=python&level=medium (fonctionne)

nouvelle URL : https://static-items.algorea.org/files/checkouts/bb3471a19ecc5f3ddf5f5575aeec3516/01_sequence_05_course/index_codecast.html?language=python&level=medium (ne fonctionne pas et affiche toujours le niveau "basic"

**Comment by remisharrock** [comment]
@mblockelet j'arrive à reproduire ce problème , est-ce résolvable avec le script de transformation des "anciens" vers les "nouveaux" ?
