### ISSUE TITLE
URGENT: comportement du if

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#32]
le if n'a pas le comportement voulu, est-ce possible de réparer cela rapidement ? 
https://codecast.france-ioi.org/player?id=1466379066206
sortie:
Youpi! je peux sortir car il fait beau!  
Il ne fait pas beau aujourd'hui...  
sortie attendue:
gcc if.c
remisharrock:~/workspace $ ./a.out
Youpi! je peux sortir car il fait beau!
Il ne pleut pas: tant mieux !
Merci beaucoup !

**Comment by remisharrock** [comment]
en fait c'est le !  qui ne fonctionne pas

**Comment by epixode** [comment]
Je fais au plus vite pour passer la correction en prod.

**Comment by epixode** [comment]
C'est corrigé et en ligne.

**Comment by remisharrock** [comment]
Merci, je teste dès que possible
