### ISSUE TITLE
un erreur est survenue: worker failed to initialize

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#34]
Je n'arrive pas à enregistrer les codecasts en prod, erreur au chargement:
Une erreur est survenue !

worker failed to initialize

-- sortie console:

errors.js:19 worker failed to initializewatchError$ @ errors.js:19tryCatch @ runtime.js:35invoke @ runtime.js:195prototype.(anonymous function) @ runtime.js:59next @ proc.js:185currCb @ proc.js:240takeCb @ proc.js:277put @ channel.js:56(anonymous function) @ channel.js:119emit @ channel.js:23(anonymous function) @ middleware.js:34dispatch @ applyMiddleware.js:35(anonymous function) @ proc.js:292asap.flush @ asap.js:27asap @ asap.js:15runPutEffect @ proc.js:289runEffect @ proc.js:257next @ proc.js:187currCb @ proc.js:240end @ proc.js:215task.cont @ proc.js:97next @ proc.js:196currCb @ proc.js:240(anonymous function) @ proc.js:265

**Comment by epixode** [comment]
C'est corrigé, c'était un autre oubli sur la nouvelle instance de prod, j'avais oublié la première commande de la procédure d'installation documentée dans le README.md...  Désolé pour le temps que ça t'a fait perdre !
