### ISSUE TITLE
plusieurs versions de documentation entre task codecast et printer task codecast

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#345]
peut-on utiliser la documentation ici https://static4.castor-informatique.fr/help/index.html  ?

**Comment by MarieVM** [comment]
La documentation https://static4.castor-informatique.fr/help/printer_codecast.html présente des bugs avec le bouton "Utiliser cet exemple" qui ne fonctionne pas. L'autre documentation a quasiment les mêmes articles explicatifs, pourquoi ne pas plutôt utiliser celle-ci ?

**Comment by SebastienTainon** [comment]
La fonctionnalité "Utiliser cet exemple" fonctionne à partir de Codecast 7.3.
