### ISSUE TITLE
paramétrage javascript qui ajoute des fonctions supplémentaires. 

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/codecast#348]
Problème : La documentation ne suit pas derrière. 

Pour faire apparaître des blocs d'instruction, il y a des mots clés. Par exemple, si on ne veut que le if pour blockly, il suffit de mettre "controls_if" dans le dictionnaire standardBlocks, cependant pour Python pour cette même option, tous les mots clés apparaissent : if, else et elif.
Hypothèse de solution Option 1 : Comment différencier la documentation en fonction du langage qui s’affiche ? 
Hypothèse de solution Option 2 : Comment faire en sorte que lorsque l’on demande juste un IF et pas toutes les fonctions if, else et elif.

Note : on a le même problème pour les listes (issue 40) [https://github.com/remisharrock/pythonspace/issues/40 ](url)

**Comment by SebastienTainon** [comment]
Merci @EllaHa le comportement est à présent le même sur Python : controls_if affiche uniquement le if (à partir de Codecast 7.3)
