### ISSUE TITLE
scanf %c 

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#35]
normalement le scanf %c capture également les espaces, est-ce qu'on modifie le comportement ou pas ? 

``` c
#include <stdio.h>
int main() {
    char premier;
    char deuxieme;
    char troisieme;
    scanf("%c", &premier);
    scanf("%c", &deuxieme);
    scanf("%c", &troisieme);
    printf("J'ai lu %c puis %c puis %c\n", premier, deuxieme, troisieme);
    return 0;
}
```

avec comme entrée a b c va afficher:
echo "a b c" | ./a.out
J'ai lu a puis   puis b

 avec comme entrée abc va afficher:
echo "abc" | ./a.out
J'ai lu a puis b puis c

Le codecast actuel ne capture pas les espaces : je me demande quoi faire ?

**Comment by remisharrock** [comment]
en fait, je préfère capturer les espaces car c'est plus cohérent avec l'évaluateur d'activités qui lui capture les espaces ...

**Comment by remisharrock** [comment]
on laisse tomber. trop de dév. laissons tel quel

**Comment by epixode** [comment]
This was resolved by the rewrite of scanf (128deff67922eb8f66cc76c91be4a27c004e622a).
