### ISSUE TITLE
Else keyword

### ISSUE THREAD

**Issue by MarieVM** [France-ioi/codecast#374]
We found those two issues with else that might be linked, is-it possible to do something about it ? 

-  Absence de ":" lors de sélection du mot-clé "else" sur les exercices python https://github.com/remisharrock/pythonspace/issues/11

-  dans un if en cliquant sur else l'indentation n'est pas décrémentée de 1  https://github.com/remisharrock/pythonspace/issues/10

**Comment by remisharrock** [comment]
bonjour @mathias-hiron , pouvez-vous voir si ce petit bug peut être corrigé facilement ?
merci  !

**Comment by SebastienTainon** [comment]
Hello @MarieVM @remisharrock , le ":" après else est corrigé.
Pour l'incrémentation/décrémentation automatique, l'éditeur utilisé n'est pas un parseur de syntaxe dans chaque langage utilisé. Nous n'avons pas l'information de la profondeur de l'arbre de syntaxe du code écrit, de la profondeur actuelle, etc... L'éditeur nous permet simplement d'insérer des snippets de code à des positions particulières. Un snippet de code peut comprendre une indentation mais celle-ci est générique (c'est par exemple "if" puis une condition, puis reviens à la ligne, puis indente, puis mets l'action correspondante). Il n'y a pas de détection a priori de l'endroit où l'on insère un bloc qui déclencherait ou pas une indentation conditionnelle. Ce serait possible de travailler sur quelque chose de ce genre (pas seulement pour else mais aussi pour elif d'ailleurs) mais cela demanderait du travail pour parser le code courant et comprendre sa structure.
