### ISSUE TITLE
typeError array fill is not a function

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#38]
des personnes remontent cette erreur sur le MOOC:
https://www.fun-mooc.fr/media/14671934924439364.png

forum 
https://www.fun-mooc.fr/courses/MinesTelecom/04019/session01/discussion/forum/f6e1c85482fb04d37936893dcfbe641a89efe042/threads/577371fd5f04ea272b0000a0

**Comment by epixode** [comment]
The necessary polyfill was added in 6a9d123fc163189273779858a1c642576b2edd96
