### ISSUE TITLE
printf: affichage noir

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#39]
Bonjour ! 
j'ai fait un petit test d'affichage qui écrit en noir : 
https://recorder.epixode.fr/player?id=1475141920088
ça marche avec l'ancien:
https://codecast.france-ioi.org/player?id=1467232086946
Merci !!

**Comment by epixode** [comment]
Bonjour !
Pour moi le comportement est normal, il n'y a rien dans la boîte d'entrée, donc scanf renvoit 0 sans avoir modifié mot1 et mot2, qui sont vides, et donc n'affichent rien.  Si j'écris deux mots dans l'éditeur d'entrée, ils s'écrivent bien dans le terminal.  Dans l'enregistrement l'entrée est vide, est-ce tu avais bien rentré du texte lors de l'enregistrement ?  Si oui, est-ce que tu te souviens si tu l'as entré avant de passer en mode enregistrement, ou pendant l'enregistrement ?  Si il y a un bug c'est de ce côté qu'il faut que je cherche.  Merci !

**Comment by remisharrock** [comment]
:-) merci je devais être fatigué
