### ISSUE TITLE
Implémentation de `scanf`

### ISSUE THREAD

**Issue by pacalet** [France-ioi/codecast#51]
`scanf` est assez compliquée parce qu'elle ce se comporte pas vraiment comme l'intuition le voudrait :

* elle consomme les blancs automatiquement lorsqu'elle cherche, par exemple, un champ numérique... mais pas lorsqu'elle lit un unique caractère ; là, elle lit un blanc,
* elle s'arrête aux blancs lorsqu'elle lit une chaîne de caractères (%s) ce qui n'est pas évident - on pourrait penser qu'elle s'arrête au premier retour à la ligne (ou a la fin du flux d'entrée),
* elle consomme tous les blancs à suivre (éventuellement aucun) lorsque la chaîne de formatage en contient un ou une suite de blancs de longueur quelconque non nulle,
* elle renonce silencieusement (si on ignore la valeur qu'elle retourne) si elle tombe sur un caractère incompatible avec la chaîne de formatage
* ...

Bref, pas facile à maîtriser en 5 minutes. L'implémentation codecast de `scanf` est assez différente de celle de la `libc` (ISO C99). On pourrait se demander si habituer les apprenants à un comportement non conforme est vraiment une bonne idée, mais admettons que ce ne soit pas un problème. Ca le devient lorsque les apprenants n'utilisent pas que le codecast. Dans le MOOC [ABC du langage C](https://www.fun-mooc.fr/courses/MinesTelecom/04019S02/session02/about), par exemple, la validation finale des exercices utilise `gcc`et de nombreux apprenants ne comprennent pas pourquoi leur code fonctionne dans le codecast mais n'est pas validé, du fait de ces différences d'implémentation. Par exemple, lorsqu'on leur demande d'acquérir un flottant puis un caractère dans le flux d'entrée

    1.0 a

le code :

```
#include <stdio.h>
int main() {
    double d;
    char c;
    scanf("%lf", &d);
    scanf("%c", &c);
    printf("|%lf| |%c|", d, c);
    return 0;
}
```

produit la sortie :

    |1.000000| |a|

avec le codecast alors qu'avec gcc on obtient :

    |1.000000| | |

Je n'ai pas de solution mais je pense qu'il serait utile de réfléchir à ces différences et aux problèmes qu'elles posent aux apprenants.

**Comment by epixode** [comment]
J'obtiens des résultats opposés aux votres :

* avec codecast le %c lit ' '
* avec la glibc le %c lit 'a'

Le scanf de codecast ne consomme pas les espaces après le traitement d'un specificateur de format mais seulement avant (sauf %c qui ne consomme pas d'espaces) .

La libc de openbsd se comporte comme codecast, ce comportement de scanf ne semble pas standardisé.

**Comment by mathias-hiron** [comment]
Bonjour,

L'implémentation de scanf et de printf dans codecast est très allégée par rapport aux implémentations usuellles. Outre le fait que seul un petit nombre de formats est supporté, il n'y a pas eu de véritable réflexion sur la manière de gérer les aspects non standardisés. Dans le cas présenté il se trouve que cela se comporte comme la libc de openbsd, mais c'est plus une coïncidence qu'un choix délibréré.

Développer une version plus complète de scanf et printf, et la rendre conformes au comportement de certaines implémentations existantes demanderait un temps significatif est n'est pas prévu actuellement.

**Comment by pacalet** [comment]
@epixode : alors nous n'avons pas la même version du codecast et de la glibc (je viens de revérifier car vous m'avez mis un doute ;-)).

**Comment by pacalet** [comment]
@mathias-hiron : je comprends parfaitement qu'il ne soit pas prévu de développer une version complète de `scanf`. Mais peut-être existe-t-il un moyen moins compliqué de contourner le problème. On pourrait, par exemple, déclencher des *warnings* lorsqu'un spécificateur de format n'est pas associé. Ou ajouter des mises en garde ici ou là. Ou autre chose de simple.

**Comment by epixode** [comment]
Effectivement l'implémentation de scanf a changée récemment afin de pouvoir lire l'entrée de manière interactive depuis un terminal (à la place d'une pré-tokenization qui a l'effet que vous observez).

Pour la glibc vous avez raison, je ne reproduis pas mon résultat.

Une version généralement à jour avec la branche master (instable, à ne pas utiliser en production) est testable ici : https://codecast.france-ioi.org/next/

**Comment by epixode** [comment]
Scanf was re-written in 128deff67922eb8f66cc76c91be4a27c004e622a to behave like a standard implementation.  You can use a version incorporating these changes at https://codecast.france-ioi.org/v5/ (and also /next/).

If you notice incompatibilities, feel free to open a new issue.
