### ISSUE TITLE
Débordements de mémoire

### ISSUE THREAD

**Issue by pacalet** [France-ioi/codecast#52]
Le codecast exécute le code suivant :

```
#include <stdio.h>
int main() {
    int t[0];
    for(int i=0; i< 10; i++) {
      t[i] = i;
      printf("%d ", t[i]);
    }
    return 0;
}
```

sans erreur et produit la sortie :

    0 1 2 3 4 5 6 7 8 9 

Alors qu'avec gcc :

    $ gcc -o memory memory.c
    $ ./memory 
    Segmentation fault: 11

Cette différence de comportement provoque une grande perplexité chez les apprenants du MOOC [ABC du langage C](https://www.fun-mooc.fr/courses/MinesTelecom/04019S02/session02/about).

**Comment by epixode** [comment]
Le comportement de ce programme n'est pas défini par le langage C. Sur une architecture sans protection mémoire il n'y aurait pas de segfault mais execution de code aléatoire. Codecast ne met pas ses pointeurs de retours sur la pile, c'est pour cela que son comportement n'est pas perturmé (mais la mémoire est bien corrompue).

**Comment by mathias-hiron** [comment]
Bonjour,

un même programme écrit un langage C peut avoir des comportements différents selon l'environnement, et la seule véritable solution pour éviter la perplexité des apprenants, est de bien leur expliquer ce point.

Les apprenants seront tout aussi perplexes s'ils utilisent chez eux un autre compilateur que gcc par exemple. Nous recevons souvent des messages d'utilisateurs qui ont un programme faux, mais sont surpris qu'il fonctionne chez eux mais pas lorsqu'ils soumettent. Il n'y a pas d'autre choix que de leur faire comprendre que ces comportements différents sont souvent les signes de variables mal initialisées ou d'écritures en dehors de zones réservées lors de manipulations de tableaux ou de pointeurs.
