### ISSUE TITLE
Boucles `for`

### ISSUE THREAD

**Issue by pacalet** [France-ioi/codecast#53]
Le codecast plante sur le code suivant :

```
#include <stdio.h>
int main() {
    int i=0;
    for(; i< 10; i++) {
      printf("%d ", i);
    }
    return 0;
}
```

**Comment by epixode** [comment]
Effectivement l'arbre de syntaxe retourné par c-to-json est incorrect et codecast se perd.

Merci pour ce rapport de bug, ce sera bientôt corrigé.

**Comment by epixode** [comment]
This is fixed in /v5/.
