### ISSUE TITLE
Compiler errors not displaying during recording playback in "next"

### ISSUE THREAD

**Issue by petraBT** [France-ioi/codecast#67]
Hello Mathias and Sebastian,

This is Petra - we just had a very productive week working with Rémi and Ella on codecasts and such. I noticed a bug in version next: 

I created a codecast in which I purposefully included a compiler error during recording. But when I play back the codecast the compiler error does not show up - only my audio describing it. You can see this at 1:22 in the codecast

https://codecast.france-ioi.org/next/player?base=https%3A%2F%2Ffioi-recordings.s3.amazonaws.com%2Fdartmouth%2F1510348172997

Thanks- Petra

**Comment by epixode** [comment]
Hello Petra,
Thank you for the report, this is fixed and your recording now shows the compiler error.

**Comment by petraBT** [comment]
Hi Sebastian,

Wow - thank you so much! You are absolutely amazing. It’s such a pleasure to record with codecast!

Thanks and best- Petra

On Nov 11, 2017, at 3:32 AM, Sébastien Carlier <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello Petra,
Thank you for the report, this is fixed and your recording now shows the compiler error.
