### ISSUE TITLE
memory coloring incorrect in codecast version next during playback

### ISSUE THREAD

**Issue by petraBT** [France-ioi/codecast#68]
Hi Sebastian,

I just noticed a funny color issue with the memory visualization. In this codecast
https://codecast.france-ioi.org/next/player?base=https%3A%2F%2Ffioi-recordings.s3.amazonaws.com%2Fdartmouth%2F1510348172997
at 4:25 a variable e = a+c was just declared and during recording, the memory locations for a and c show up in green since they were just read from, but in playback, everything is colored red. Also, the entire memory that has been used is red versus just the locations used in the latest step. This may be an issue that happened after hitting the 'pause' button during recording - not entirely sure?

Thanks- Petra

**Comment by epixode** [comment]
Hi Petra,
Thank you for the report!
The player failed to properly clear the memory log (used to show changes in memory) between steps.
I think I have just fixed this.  Please let me know if your codecast now plays as expected.

**Comment by petraBT** [comment]
It works perfectly now. Fantastic! Thanks so much, Sébastien!

—Petra

On Nov 11, 2017, at 1:40 PM, Sébastien Carlier <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Petra,
Thank you for the report!
The player failed to properly clear the memory log (used to show changes in memory) between steps.
I think I have just fixed this. Please let me know if your codecast now plays as expected.
