### ISSUE TITLE
interactive mode not working properly in version next

### ISSUE THREAD

**Issue by petraBT** [France-ioi/codecast#70]
In version next, when user input is requested using scanf(), what the user types does not show up until they hit "return". Example:

#include <stdio.h>

int main(void) {
    int a;
    scanf("%d", &a);
    return(0);
}

**Comment by remisharrock** [comment]
Any work on this ? There is still the bug.
Thanks

**Comment by epixode** [comment]
Now fixed in /v5 and /next.
