### ISSUE TITLE
scanf("%d%d", &a, &b); not working properly in version next

### ISSUE THREAD

**Issue by petraBT** [France-ioi/codecast#71]
In version next, the above creates an error. In v3, it creates a non-responsive program. When a space is added between the %d's  ("%d %d"), then v3 behaves properly. In version next however, one has to input the two numbers in one line and cannot hit return between the two numbers.

**Comment by remisharrock** [comment]
I add that we tried with "interactive mode" for the terminal

**Comment by epixode** [comment]
I just updated /next with a new implementation of scanf whose behavior is much closer to a standard implementation.  I'll document exactly what features are supported (in short: width field on all specifiers, * modifier, l/ll/h size field where it makes sense, literal characters, scansets and negated scansets, accurate handling of whitespace, and accurate behavior for %c %s %d %x %o %f %i %u specifiers; %% and %n are not supported yet but will be added).

There is still an issue with the interactive terminal where the wrong state gets restored when scanf does not get all its input on a single line.  I will fix this now.

**Comment by petraBT** [comment]
Fantastic - thank you! So excited about this improvement. I noticed that "%d%d" works well (except for input over multiple lines in interactive mode as you note), but "%c%c" does not (neither does "%c%d"). Both lead to an error message "TypeError: C.ArrayValue is not a constructor". Let me know if you need more details. Thank you so much for working on this!

**Comment by epixode** [comment]
Thanks Petra for the report!  I had forgotten to push the update the C core to export ArrayValue.  I just did so and %c should work for you now.

**Comment by epixode** [comment]
Input over multiple lines in interactive mode should also work now!

Also, scanf now returns a meaningful value, previously a typo made it always return 0.
In addition, specifiers %% and %n are now supported

Please be sure to let me know if you notice further issues!

**Comment by petraBT** [comment]
Thank you, Sébastian! There is still an issue when there are multiple scanf() statements following each other as the following example demonstrates:
![screen shot 2018-02-09 at 1 37 17 pm](https://user-images.githubusercontent.com/33522257/36043863-baa0adfc-0d9e-11e8-9423-0529a5521a5c.png)

**Comment by epixode** [comment]
Thanks Petra!  I had made a small mistake that caused input not to be consumed, so that "%d%d" in a single scanf() worked fined, but multiple scanf() statements behaved incorrectly.  This is now fixed and I verified that the example you just gave works correctly.  Again, thank you, your bug reports are very clear and helpful!

**Comment by petraBT** [comment]
Sébastian, this is fantastic! Thank you so much! scanf() behaves now exactly as 'in the real world', this is so exciting!! I tested everything I can think of, it's really wonderful. You are amazing!

**Comment by remisharrock** [comment]
great news ! thanks @epixode !!
