### ISSUE TITLE
v5 and v5/player/recorder look different

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#76]
It looks like 
https://codecast.france-ioi.org/v5/
and 
https://codecast.france-ioi.org/v5/recorder
or the player
https://codecast.france-ioi.org/v5/player?base=https%3A%2F%2Ffioi-recordings.s3.amazonaws.com%2Fguest%2F1513350014195
have different GUI designs ?

**Comment by epixode** [comment]
Yes, different bits of code are used to produce the interfaces, because they have different sets of controls (some of which are shared).
