### ISSUE TITLE
pause in the next version generates an error

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#77]
in the next version, when I click the pause button here is the error:

audioContextResumed 11
client.js:775 GET https://codecast.france-ioi.org/next/undefined.json 404 (Not Found)
Request._end @ client.js:775
Request.end @ client.js:679
(anonymous) @ utils.js:17
F @ _export.js:35
getJson @ utils.js:14
runCallEffect @ proc.js:503
runEffect @ proc.js:425
next @ proc.js:306
currCb @ proc.js:378
runForkEffect @ proc.js:551
runEffect @ proc.js:425
next @ proc.js:306
currCb @ proc.js:378
(anonymous) @ proc.js:489
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:476
runEffect @ proc.js:425
next @ proc.js:306
currCb @ proc.js:378
end @ proc.js:346
task.cont @ proc.js:99
next @ proc.js:312
currCb @ proc.js:378
cpsCb @ proc.js:521
(anonymous) @ worker_utils.js:33
listener @ eventemitter2.js:264
EventEmitter.emit @ eventemitter2.js:328
_ref @ worker_utils.js:18
undefined.mp3:1 GET https://codecast.france-ioi.org/next/undefined.mp3 404 (Not Found)
utils.js:225 watchAudioCanPlay has been cancelled 
errors.js:17 {err: Error: Not Found
    at Request.<anonymous> (https://codecast.france-ioi.org/next/build/vendor.js:15…, res: Response}
watchError$ @ errors.js:17
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.(anonymous function) @ runtime.js:114
next @ proc.js:302
currCb @ proc.js:378
takeCb @ proc.js:456
put @ channel.js:73
(anonymous) @ channel.js:161
(anonymous) @ channel.js:182
emit @ channel.js:26
(anonymous) @ middleware.js:67
dispatch @ applyMiddleware.js:35
(anonymous) @ utils.js:250
(anonymous) @ proc.js:479
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:476
runEffect @ proc.js:425
next @ proc.js:306
currCb @ proc.js:378
end @ proc.js:346
abort @ proc.js:79
task.cont @ proc.js:92
next @ proc.js:319
currCb @ proc.js:378
(anonymous) @ proc.js:441
Promise rejected (async)
resolvePromise @ proc.js:440
runCallEffect @ proc.js:507
runEffect @ proc.js:425
next @ proc.js:306
currCb @ proc.js:378
runForkEffect @ proc.js:551
runEffect @ proc.js:425
next @ proc.js:306
currCb @ proc.js:378
(anonymous) @ proc.js:489
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:476
runEffect @ proc.js:425
next @ proc.js:306
currCb @ proc.js:378
end @ proc.js:346
task.cont @ proc.js:99
next @ proc.js:312
currCb @ proc.js:378
cpsCb @ proc.js:521
(anonymous) @ worker_utils.js:33
listener @ eventemitter2.js:264
EventEmitter.emit @ eventemitter2.js:328
_ref @ worker_utils.js:18
recorder:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.
Promise (async)
playerPrepare$ @ sagas.js:107
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.(anonymous function) @ runtime.js:114
next @ proc.js:302
currCb @ proc.js:378
runForkEffect @ proc.js:551
runEffect @ proc.js:425
next @ proc.js:306
currCb @ proc.js:378
(anonymous) @ proc.js:489
exec @ scheduler.js:19
flush @ scheduler.js:60
asap @ scheduler.js:33
runPutEffect @ proc.js:476
runEffect @ proc.js:425
next @ proc.js:306
currCb @ proc.js:378
end @ proc.js:346
task.cont @ proc.js:99
next @ proc.js:312
currCb @ proc.js:378
cpsCb @ proc.js:521
(anonymous) @ worker_utils.js:33
listener @ eventemitter2.js:264
EventEmitter.emit @ eventemitter2.js:328
_ref @ worker_utils.js:18

**Comment by epixode** [comment]
Odd that it is looking for undefined.json and undefined.mp3, can you provide the full URL so that I can reproduce?  Thanks!

**Comment by remisharrock** [comment]
well, I just go to 
https://codecast.france-ioi.org/next/recorder
start a recording and pause

**Comment by epixode** [comment]
I had assumed the issue was in the player because the stack trace mentions watchAudioCanPlay, which is used only in the player.

I understand what happens now and should be able to fix it.

**Comment by epixode** [comment]
Pausing during recording is fixed in /next.

**Comment by remisharrock** [comment]
a priori ça fonctionne au premier test, merci ! 
Je ferai des tests en profondeur plus tard

**Comment by remisharrock** [comment]
Thanks, it works now!
