### ISSUE TITLE
error after recording and uploading ?

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#78]
I cannot play this codecast : 

https://fioi-recordings.s3.amazonaws.com/guest/1516194730570.json

https://fioi-recordings.s3.amazonaws.com/guest/1516194730570.mp3

https://codecast.france-ioi.org/v5/player?base=https%3A%2F%2Ffioi-recordings.s3.amazonaws.com%2Fguest%2F1516194730570

**Comment by epixode** [comment]
The codecast was recorded with /next, the format has changed and cannot be played with /v5 just yet (but support is planned).

**Comment by remisharrock** [comment]
I think I recorded with /v5 ?

**Comment by epixode** [comment]
Hi,

I am looking at this again and noticed that the audio file is truncated (it is only 384 bytes).  Is it possible that the upload failed for some reason?

Have you been able to make other recording with /v5, or was there an issue with this recording only?

Thanks,

**Comment by remisharrock** [comment]
Maybe it was a temporary error, I did it again a few days after and it worked !
thanks
