### ISSUE TITLE
PLAYER en Intégration iframe sur FUN changer le responsive design

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#8]
Après intégration en iframe sur FUN , le seuil pour le responsive design en largeur s'avère être une autre valeur. Voir la page dans le zip suivant:
[page integration iframe](https://partage.mines-telecom.fr/public.php?service=files&t=6dcfc3f37fb659541bbc1f303f49121f)  (cliquer sur le bouton télécharger en haut à droite)

**Comment by epixode** [comment]
L'intégration au bon format est en cours, la disposition des éléments et la quantité d'information affichée sera préservée en réduisant légèrement la taille des polices et des marges.

**Comment by epixode** [comment]
Closing this issue assuming it has been fixed, feel free to re-open with more details.
