### ISSUE TITLE
v5 and next: printf doesn't work in split mode

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#82]
in v5 and next, printf doesn't work in split mode:
https://codecast.france-ioi.org/next/player?base=https%3A%2F%2Ffioi-recordings.s3.amazonaws.com%2Fguest%2F1518473525395

**Comment by epixode** [comment]
Fixed in /v5, possibly a bug it a dependency but fortunately there was a simple work-around.  Thank you  for the report!
