### ISSUE TITLE
next recorder produces guest recording even if connected

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#83]
If i create a recording even if I'm connected with version next, I get a "guest" player link at the end. 
Example: 
connected to next with "remisharrock"
produced link
https://codecast.france-ioi.org/next/player?base=https%3A%2F%2Ffioi-recordings.s3.amazonaws.com%2Fguest%2F1518473758555

**Comment by epixode** [comment]
A change was needed to match the new login-module profile resource API, it should work as expected now.
