### ISSUE TITLE
v5 compilation gives undefined

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#86]
When I compile with v5 it gives me "undefined" error as a message.
I guess it's because of the move from next to v5 happening right now ?

**Comment by remisharrock** [comment]
now the v5 is a 502 Bad Gateway; so that's definitely an upgrading going on right now...

**Comment by epixode** [comment]
Indeed, it will be back shortly, thank you for your patience ☺

**Comment by remisharrock** [comment]
🔢 excited and impatient to test !

**Comment by epixode** [comment]
It should be all good now, please let me know if you encounter any blocking issue!
