### ISSUE TITLE
green appearing when playing back

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/codecast#88]
It looks like a little bit of green is appearing on the playback even if it was not in execution mode
: 
https://codecast.france-ioi.org/v5/player?base=https%3A%2F%2Ffioi-recordings.s3.amazonaws.com%2Fdartmouth%2F1518612236861

at 8min

look at the two pictures:

![image](https://user-images.githubusercontent.com/8048877/36269026-1aeb3320-1246-11e8-943b-7f2105d9b46b.png)

![image](https://user-images.githubusercontent.com/8048877/36269072-3ae18dbe-1246-11e8-9c38-bfd9362af376.png)

**Comment by epixode** [comment]
Fixed by https://github.com/France-ioi/codecast/commit/2336f03b56f94690abeaeaeb18de4e931d6ff71f
