### ISSUE TITLE
linked lists: NULL pointers and typedef

### ISSUE THREAD

**Issue by petraBT** [France-ioi/codecast#94]
Would it be possible to implement NULL pointers and typedef so as to be able to introduce linked lists via codecast? Since structures are now possible in codecast this seems so close! Below is a sample program that would be fantastic to be able to run. I actually tried to get around typedef and NULL by replacing NULL with '\0' and simply using struct digit instead of the type, but the program still didn't work in codecast (I am pasting the second version below the first version). It compiled but no run buttons appeared. Thanks!

#include <stdio.h>
#include <stdlib.h>

struct digit     /* structure to hold digits in linked list */
{
	int num;
	struct digit *next;
};

typedef struct digit digit_t;

digit_t *readNumber(void);                   /* prototypes */
void displayNumber(digit_t *number);
void destroyNumber(digit_t *number);
     
int main(void) {
	digit_t *number;	
	printf("Please enter an integer of any length: ");
	number = readNumber();
	if (number != NULL) {
		printf("Thank you!\n");
    		printf("You entered the following number: \n");
		displayNumber(number);
		destroyNumber(number);
	}
	else printf("You didn't enter anything.\n");
        return(0);
}

/* Function to create linked list of digits of number */
digit_t *readNumber(void) {
    char c;   
    int d;     
    digit_t *start, *end, *new; 					      
    start = NULL;   
    scanf("%c", &c);   
    while (c != '\n') {
		d = c-48;    
                new = (digit_t *)malloc(sizeof(digit_t));
		new->num = d;      
		new->next = NULL;          
                if (start == NULL) {  
			start = new;
			end = start;            
		}
                else {               
			end->next = new;
			end = end->next;
                }
	        scanf("%c", &c);     
    }
    return(start);        
}

/* Function to display the number */
void displayNumber (digit_t *number) {	
        digit_t *current;
	current = number;
	while (current != NULL)	{
		printf("%d", current->num);
		current = current->next;
        }
       printf("\n");
}
   
/* Function to free the number (all of its digits) */
void destroyNumber (digit_t *number) {
	digit_t *current, *temp;	
	current = temp = number;
	while (current != NULL) {
		current = current -> next;
        	free(temp);
		temp = current;
	}
}

/* -------------------------------------------------- */
/* -------------------------------------------------- */

/* Second version without typedef or NULL */

#include <stdio.h>
#include <stdlib.h>

struct digit     
{
	int num;
	struct digit *next;
};

struct digit *readNumber(void);                   
void displayNumber(struct digit *number);
void destroyNumber(struct digit *number);
     
int main(void) {
	struct digit *number;	
	printf("Please enter an integer of any length: ");
	number = readNumber();
	if (number != '\0') {
		printf("Thank you!\n");
    		printf("You entered the following number: \n");
		displayNumber(number);
		destroyNumber(number);
	}
	else printf("You didn't enter anything.\n");	
        return(0);
}

/* Function to create linked list of digits of number */
struct digit *readNumber(void) {
    char c;  
    int d;    
    struct digit *start, *end, *new;  
    start = '\0';  
    scanf("%c", &c);  
    while (c != '\n') {
		d = c-48;   
                new = (struct digit *)malloc(sizeof(struct digit));
		new->num = d;      
		new->next = '\0';        
                if (start == '\0') {  
			start = new;
			end = start;            
		}
                else {               
			end->next = new;
			end = end->next;
                }
	        scanf("%c", &c);    
    }
    return(start);        
}

/* Function to display the number */
void displayNumber (struct digit *number) { 	
        struct digit *current;	
	current = number;
	while (current != '\0')	{
		printf("%d", current->num);
		current = current->next;
        }
        printf("\n");
}

/* Function to free the number (all of its digits) */
void destroyNumber (struct digit *number) {
	struct digit *current, *temp;	
	current = temp = number;
	while (current != '\0') {
		current = current -> next;
        	free(temp);
		temp = current;
	}
}

**Comment by epixode** [comment]
Petra,

The interpreter is lacking support for clang's ElaboratedType node type, I will add it and see if it resolves the issue.  I don't see anything else that would prevent your second version from working.

Typedef support requires a little more work but we'll support it eventually.

By the way, I should point out that '\0' is the NUL character, which is distinct from the NULL pointer. 
 When relying on implicit transtyping rules it is less confusing to write just 0 unless it's for the IOCCC :)
I will add the definition for NULL to stddef.h, until then you can simply add it to the start of your program:

#define NULL ((void*) 0)

**Comment by petraBT** [comment]
Thanks so much, Sébastian! Getting linked lists working in codecast would be amazing. And if typedef becomes a possibility, even better!! Thanks!

**Comment by epixode** [comment]
Petra,

No typedefs yet, but recursive structs are now supported in /next:

    #include <stdio.h>
    #include <stdlib.h>
    
    struct digit
    {
        int num;
        struct digit *next;
    };
    
    struct digit *readNumber(void);
    void displayNumber(struct digit *number);
    void destroyNumber(struct digit *number);
    
    int main(void) {
        struct digit *number;
        printf("Please enter an integer of any length: ");
        number = readNumber();
        if (number != NULL) {
            printf("Thank you!\n");
            printf("You entered the following number: \n");
            displayNumber(number);
            destroyNumber(number);
        }
        else printf("You didn't enter anything.\n");
        return(0);
    }
    
    /* Function to create linked list of digits of number */
    struct digit *readNumber(void) {
        char c;
        int d;
        struct digit *start, *end, *new;
        start = NULL;
        scanf("%c", &c);
        while (c != '\n') {
            d = c-48;
            new = (struct digit *)malloc(sizeof(struct digit));
            new->num = d;
            new->next = NULL;
            if (start == NULL) {
                start = new;
                end = start;
            }
            else {
                end->next = new;
                end = end->next;
            }
            scanf("%c", &c);
        }
        return(start);
    }
    
    /* Function to display the number */
    void displayNumber (struct digit *number) {
        struct digit *current;
        current = number;
        while (current != NULL)	{
            printf("%d", current->num);
            current = current->next;
        }
        printf("\n");
    }
    
    /* Function to free the number (all of its digits) */
    void destroyNumber (struct digit *number) {
        struct digit *current, *temp;
        current = temp = number;
        while (current != NULL) {
            current = current -> next;
            free(temp);
            temp = current;
        }
    }

I noticed there was an issue with comparison of pointers, now resolved.

**Comment by petraBT** [comment]
This is so exciting!! Thank you so much!!!

**Comment by epixode** [comment]
Closing this as it is resolved except for typedef, for which I'll open a distinct issue for clarity.
