### ISSUE TITLE
Initializing structures in codecast v5

### ISSUE THREAD

**Issue by petraBT** [France-ioi/codecast#95]
The following generates an error during execution ("TypeError: Cannot read property 'size' of undefined") - is this something that can be addressed?

Thanks!!

#include <stdio.h>

struct student{
	char firstName[30];
	char lastName[30];
	int birthYear;
	double aveGrade;
};

int main(void) {
	struct student stud1={"Petra", "Bonfert-Taylor", 1989, 3.5};
	
	printf("Name: %s %s\n", stud1.firstName, stud1.lastName);
	printf("Year of birth: %d\n",stud1.birthYear);
	printf("Average grade: %.2lf\n",stud1.aveGrade);
	return 0;
}

**Comment by petraBT** [comment]
More generally, there seems to be an issue with structures containing arrays as members (I think). The following code compiles but then stalls when even trying to simply print the address of the first string:
#include <stdio.h>

void strcpy1(char *source, char *target);
struct student{
	char firstName[30];
	char lastName[30];
	int birthYear;
	double aveGrade;
};

int main(void) {
    //! showMemory(start=65520)

	struct student stud1;
	printf("Student1 stored at %p.\n", &stud1);
	printf("  firstName at: %p\n",stud1.firstName);
	printf("  lastName at: %p\n", stud1.lastName);
	printf("  birthYear at: %p\n", &(stud1.birthYear));
	printf("  aveGrade at: %p\n", &(stud1.aveGrade));
	stud1.birthYear = 1989;
	stud1.aveGrade = 3.5;
	strcpy1("Petra", stud1.firstName);
	strcpy1("Bonfert-Taylor", stud1.lastName);
	
	printf("Name: %s %s\n", stud1.firstName, stud1.lastName);
	printf("Year of birth: %d\n",stud1.birthYear);
	printf("Average grade: %.2lf\n",stud1.aveGrade);
	return 0;
}

void strcpy1(char *source, char *target) {
    int i = 0;
    while (source[i]!='\0') {
        target[i] = source[i];
        i++;
    }
    target[i] = '\0';
}

**Comment by epixode** [comment]
Petra,

Your first program above now works on /next.

These features used by your example were missing:

* Support for initialization lists for structs
* Support for initialization of arrays from string literals
* Support for constructing a reference to a composite type within a struct

I also added support for displaying struct members inside the showMemory() view, but I am not sure how to display labels "stud1.firstName[0]" "stud1.firstName[1]" and so on.  Currently they all overlap and the result is illegible.

Also, initialization from a string literal copies as all chars needed to fill the destination array, which is confusing but, I think, technically not wrong (the '\0' from the string literal is copied, so your first example above shows the correct output).  I will try to fix this to copy the minimum number of characters.

Finally, initializing an incomplete-type array from a string literal is not handled, so I expect this line to fail (but I will fix it shortly):

    char foo[] = "bar";

**Comment by epixode** [comment]
I see from your second example that there is a problem with uninitialized structs, and also with implicit values in initialization lists for structs.  I will add support for these.

**Comment by petraBT** [comment]
Wow - fantastic!!

Would it make sense to only show stud1.firstName at the beginning of the character array and where last name starts (rather than showing a label for each individual character)?

Thanks- Petra


On Feb 27, 2018, at 11:50 AM, Sébastien Carlier <notifications@github.com<mailto:notifications@github.com>> wrote:


Petra,

Your first program above now works on /next.

These features used by your example were missing:

  *   Support for initialization lists for structs
  *   Support for initialization of arrays from string literals
  *   Support for constructing a reference to a composite type within a struct

I also added support for displaying struct members inside the showMemory() view, but I am not sure how to display labels "stud1.firstName[0]" "stud1.firstName[1]" and so on. Currently they all overlap and the result is illegible.

Also, initialization from a string literal copies as all chars needed to fill the destination array, which is confusing but, I think, technically not wrong (the '\0' from the string literal is copied, so your first example above shows the correct output). I will try to fix this to copy the minimum number of characters.

Finally, initializing an incomplete-type array from a string literal is not handled, so I expect this line to fail (but I will fix it shortly):

char foo[] = "bar";

**Comment by petraBT** [comment]
Not sure whether this is a separate issue or will be fixed by the above, but currently it doesn't seem to work to pass a structure to a function:

#include <stdio.h>

struct student{
	char firstName[30];
	char lastName[30];
	int birthYear;
	double aveGrade;
};
void printStudent(struct student);
int main(void) {
	struct student stud1={"Petra", "Bonfert-Taylor", 1989, 3.5};
	struct student stud2={"Remi", "Sharrock", 1992, 3.5};
	printStudent(stud1);
	printStudent(stud2);
	return 0;
}

void printStudent(struct student stud) {
    printf("Name: %s %s\n", stud.firstName, stud.lastName);
	printf("Year of birth: %d\n",stud.birthYear);
	printf("Average grade: %.2lf\n",stud.aveGrade);
}

**Comment by epixode** [comment]
Passing a struct by value (copy) requires special care, I am not surprised it does not work (yet, I will look at it).

Passing structs by reference works:

    #include <stdio.h>
    
    struct student {
        char firstName[30];
        char lastName[30];
        int birthYear;
        double aveGrade;
    };
    void printStudent(struct student *);
    
    int main(void) {
        struct student stud1={"Petra", "Bonfert-Taylor", 1989, 3.5};
        struct student stud2={"Remi", "Sharrock", 1992, 3.5};
        printStudent(&stud1);
        printStudent(&stud2);
        return 0;
    }
    
    void printStudent(struct student * stud) {
        printf("Name: %s %s\n", stud->firstName, stud->lastName);
        printf("Year of birth: %d\n",stud->birthYear);
        printf("Average grade: %.2lf\n",stud->aveGrade);
    }

**Comment by petraBT** [comment]
Very cool! This is next in my pedagogy! I’d like to first show students that structures can be thought of as ‘normal’ variables (pretty much) with respect to their behavior with functions and then teach them that despite this fact it is preferable from an efficiency standpoint to always pass them by reference.

Thanks!!

On Feb 27, 2018, at 12:40 PM, Sébastien Carlier <notifications@github.com<mailto:notifications@github.com>> wrote:


Passing a struct by value (copy) requires special care, I am not surprised it does not work (yet, I will look at it).

Passing structs by reference works:

#include <stdio.h>

struct student {
    char firstName[30];
    char lastName[30];
    int birthYear;
    double aveGrade;
};
void printStudent(struct student *);

int main(void) {
    struct student stud1={"Petra", "Bonfert-Taylor", 1989, 3.5};
    struct student stud2={"Remi", "Sharrock", 1992, 3.5};
    printStudent(&stud1);
    printStudent(&stud2);
    return 0;
}

void printStudent(struct student * stud) {
    printf("Name: %s %s\n", stud->firstName, stud->lastName);
    printf("Year of birth: %d\n",stud->birthYear);
    printf("Average grade: %.2lf\n",stud->aveGrade);
}

**Comment by epixode** [comment]
I understand, makes sense.  It shouldn't take much to get passing structs by-value to work, the mechanisms to support it are already in place.  I'll try to find what's going wrong later today.

**Comment by epixode** [comment]
I fixed these issues mentioned above: over-initialization from string literals, support for uninitialized and partially initialized structs, support for passing structs by value.  The examples you gave all work, so I'll go ahead and close this issue.

The display of struct labels in the memory view will require more thought, only showing the label for the first cell of an array in a struct may be part of the solution, but perhaps a more general approach can be designed to handle the case where the user has scrolled past the start of an array.

Thanks for the reports and examples!
