### ISSUE TITLE
display does not refresh when using structures

### ISSUE THREAD

**Issue by petraBT** [France-ioi/codecast#97]
The strangest thing happens when executing the following code: All output to the terminal window is withheld until the very end of the program.

#include <stdio.h>

struct student{
	char firstName[30];
	char lastName[30];
	int birthYear;
	double aveGrade;
};

void copyStr(char *, char *);
void printStudent(struct student);
int main(void) {
    //! showMemory(start=65520)
	struct student stud1;
	printf("First name: ");
	scanf("%s", stud1.firstName);
	printf("Last name: ");
	scanf("%s", stud1.lastName);
	printf("Year of birth: ");
	scanf("%d", &stud1.birthYear);
	printf("Average grade: ");
	scanf("%lf", &stud1.aveGrade);
	
	printStudent(stud1);
	return 0;
}

void copyStr(char *source, char *target) {
    int i = 0;
    while (source[i]!='\0') {
        target[i] = source[i];
        i++;
    }
    target[i] = '\0';
}

void printStudent(struct student stud) {
    printf("Name: %s %s\n", stud.firstName, stud.lastName);
	printf("Year of birth: %d\n",stud.birthYear);
	printf("Average grade: %.2lf\n",stud.aveGrade);
}

**Comment by petraBT** [comment]
Sorry - here is a simpler code that shows the same issues. Maybe it's related to strings as members of structures?

#include <stdio.h>

struct student{
	char firstName[30];
	char lastName[30];
	int birthYear;
	double aveGrade;
};

int main(void) {
	//! showMemory(start=65520)
	struct student stud1={"Petra", "Bonfert-Taylor", 1989, 3.5};
	
	printf("Name: %s %s\n", stud1.firstName, stud1.lastName);
	printf("Year of birth: %d\n",stud1.birthYear);
	printf("Average grade: %.2lf\n",stud1.aveGrade);
	return 0;
}

**Comment by epixode** [comment]
The stack view was accessing a field that was removed from the evaluator's data structure during recent changes, causing the view not to refresh.

Fixed by https://github.com/France-ioi/codecast/commit/9849f01a03be6eff248d7dea0b434b30ea903054

Thanks Petra!
