### ISSUE TITLE
sizeof() for members of structures

### ISSUE THREAD

**Issue by petraBT** [France-ioi/codecast#98]
The following code stalls when it gets to the execution of sizeof(stud1.firstName)

#include <stdio.h>

struct student{
	char firstName[30];
	char lastName[30];
	int birthYear;
	double aveGrade;
};

int main(void) {
    //! showMemory(start=65520)
	struct student stud1;
	printf("Size of struct student is %zu.\n", sizeof(struct student));
	printf("Size of firstName is %zu.\n", sizeof(stud1.firstName));
}

**Comment by epixode** [comment]
Fixed by https://github.com/epixode/persistent-c/commit/2db4eb1872d6ddc8f1a0385bd3bee66f64f128d8
